name: firebase_hosting_deploy
on:
  workflow_dispatch:
    branches:
      - live
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build
        working-directory: website
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KARAS_COFFEE }}'
          channelId: live
          projectId: karas-coffee
          entryPoint: website
